#!/usr/bin/env python3
# make_synthetic.py — 生成明确标记的模拟数据集(不来源于任何真实患者,
# 不扰动真实数据,不保留真实分布中的可识别模式)。
# 输出仅用于测试代码执行,不构成研究估计。
import os
import numpy as np
import pandas as pd

SEED = 20260726
rng = np.random.default_rng(SEED)
OUT = os.path.dirname(os.path.abspath(__file__))

N = 400
subject_id = np.arange(900000001, 900000001 + N)
age = np.clip(rng.normal(64, 12, N), 30, 89).round().astype(int)
sex = rng.choice(["M", "F"], N, p=[0.62, 0.38])
bmi = np.clip(rng.normal(26, 4.5, N), 16, 45).round(1)
bmi[rng.choice(N, 6, replace=False)] = np.nan  # 边界案例:BMI 缺失
diabetes = rng.binomial(1, 0.28, N)
charlson_wo_dm = rng.poisson(1.6, N)
proc = rng.choice(["isolated CABG", "isolated open valve", "combined CABG + open valve"], N,
                  p=[0.55, 0.30, 0.15])
lactate = np.clip(rng.lognormal(0.4, 0.5, N), 0.3, 12).round(1)
creat = np.clip(rng.lognormal(-0.1, 0.4, N), 0.3, 8).round(2)
sofa = np.clip(rng.poisson(5, N), 0, 18).astype(int)

# 模拟血糖序列(每人 4–14 次,锚点 t0=0,窗 [0,1440))
rows = []
for i in range(N):
    n_m = int(rng.integers(2, 15))
    base = rng.normal(140, 22)
    times = np.sort(rng.choice(np.arange(0, 1440), size=n_m, replace=False))
    vals = np.clip(base + rng.normal(0, 16, n_m), 40, 420)
    # 边界案例:完全重复与同分钟多源
    if i % 37 == 0 and n_m >= 3:
        times[1] = times[0]
        vals[1] = vals[0]
    for t, v in zip(times, vals):
        src = rng.choice(["central_lab", "blood_gas", "poct", "icu_charted"], p=[0.1, 0.45, 0.35, 0.1])
        rows.append((subject_id[i], int(t), src, round(float(v), 1)))
glu = pd.DataFrame(rows, columns=["subject_id", "minute", "source_class", "value"])

# 结局(与 GV 弱相关或不相关)
gv_true = glu.groupby("subject_id")["value"].std().reindex(subject_id).fillna(10)
lin = -2.6 + 0.25*(age-60)/10 + 0.4*diabetes + 0.15*(sofa-5)/3 + 0.05*rng.normal(0, 1, N)
p = 1/(1+np.exp(-lin))
event30 = rng.binomial(1, np.clip(p*0.06, 0.005, 0.3))
fu30 = np.where(event30==1, rng.uniform(2, 29, N), 30.0)

cohort = pd.DataFrame({
    "subject_id": subject_id, "age": age, "sex": sex, "bmi": bmi, "diabetes": diabetes,
    "charlson_without_diabetes": charlson_wo_dm, "procedure_cat6": proc,
    "lactate_postop_first": lactate, "creat_postop_first": creat, "sofa_24h": sofa,
    "t_lm_30": fu30, "event_lm_30": event30,
    "t_lm_365": np.minimum(365, fu30 + rng.uniform(100, 335, N)),
    "event_lm_365": ((rng.random(N) < 0.18) | (event30 == 1)).astype(int),
})
cohort["hba1c_pct"] = np.where(rng.random(N) < 0.45,
                               np.clip(rng.normal(6.1, 1.0, N), 4.5, 12).round(1), np.nan)
cohort["SYNTHETIC"] = True

glu.to_csv(os.path.join(OUT, "synthetic_glucose_long.csv"), index=False)
cohort.to_csv(os.path.join(OUT, "synthetic_cohort.csv"), index=False)
with open(os.path.join(OUT, "README.md"), "w") as f:
    f.write("# Synthetic data (NOT real patients)\n\n"
            "Generated by make_synthetic.py with seed 20260726.\n\n"
            "> Synthetic data are provided solely to test code execution and do not reproduce the study estimates.\n\n"
            "- No real-patient derivation, no perturbation of real data, no identifiable patterns.\n"
            "- Files: synthetic_glucose_long.csv (stay-minute source-class glucose),\n"
            "  synthetic_cohort.csv (baseline, exposure inputs, outcomes, optional HbA1c).\n"
            "- Contains deliberate edge cases: same-minute multi-source records, missing BMI.\n")
print("synthetic rows:", len(glu), "; patients:", N, "; events30:", int(event30.sum()))
