#!/usr/bin/env python3
"""Register Phase 2 estimands; do not fit any of them in Phase 1.6."""

from __future__ import annotations

import json
import sys
from pathlib import Path

WORKSPACE = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(WORKSPACE))

from src.config_loader import load_config, output_root, workspace_root  # noqa: E402
from src.schema_checks import utc_now_iso, write_csv  # noqa: E402


FIELDS = (
    "analysis_id",
    "database",
    "cohort",
    "outcome",
    "effect_type",
    "gv_metric",
    "source_definition",
    "adjustment_set",
    "existing_locked_estimate_available",
    "new_fit_required",
    "patient_level_available",
    "fit_status",
    "reason",
)


def main() -> int:
    config = load_config()
    rows = [
        {
            "analysis_id": "MIMIC_PRIMARY_MODEL_B_30D",
            "database": "MIMIC-IV",
            "cohort": "final day-1 landmark target N=10561",
            "outcome": "30-day all-cause mortality",
            "effect_type": "HR",
            "gv_metric": "GV SD per 10 mg/dL",
            "source_definition": "final source-priority series",
            "adjustment_set": "Model B final contract",
            "existing_locked_estimate_available": True,
            "new_fit_required": False,
            "patient_level_available": True,
            "fit_status": "LOCKED_RESULT_AVAILABLE",
            "reason": "Use locked final result for Phase 2 framing; no refit in Phase 1.6",
        },
        {
            "analysis_id": "MIMIC_MODEL_C_30D",
            "database": "MIMIC-IV",
            "cohort": "final day-1 landmark target N=10561",
            "outcome": "30-day all-cause mortality",
            "effect_type": "HR",
            "gv_metric": "GV SD per 10 mg/dL",
            "source_definition": "final source-priority series",
            "adjustment_set": "Model C final measurement/process covariates",
            "existing_locked_estimate_available": True,
            "new_fit_required": False,
            "patient_level_available": True,
            "fit_status": "LOCKED_RESULT_AVAILABLE",
            "reason": "Locked MICE Model C fingerprint is available; no refit in Phase 1.6",
        },
        {
            "analysis_id": "MIMIC_SOURCE_POCT_30D",
            "database": "MIMIC-IV",
            "cohort": "POCT-only source cohort",
            "outcome": "30-day all-cause mortality",
            "effect_type": "HR",
            "gv_metric": "source-specific GV SD per 10 mg/dL",
            "source_definition": "POCT-only",
            "adjustment_set": "Model B source sensitivity contract",
            "existing_locked_estimate_available": True,
            "new_fit_required": False,
            "patient_level_available": True,
            "fit_status": "LOCKED_RESULT_AVAILABLE",
            "reason": "Locked source result exists; same-patient and source cohorts remain distinct",
        },
        {
            "analysis_id": "MIMIC_SOURCE_LAB_30D",
            "database": "MIMIC-IV",
            "cohort": "central-laboratory-only source cohort",
            "outcome": "30-day all-cause mortality",
            "effect_type": "HR",
            "gv_metric": "source-specific GV SD per 10 mg/dL",
            "source_definition": "central laboratory-only",
            "adjustment_set": "Model B source sensitivity contract",
            "existing_locked_estimate_available": True,
            "new_fit_required": False,
            "patient_level_available": True,
            "fit_status": "LOCKED_RESULT_AVAILABLE",
            "reason": "Locked source result exists; not interchangeable with POCT",
        },
        {
            "analysis_id": "MIMIC_SAMEPATIENT_POCT_30D",
            "database": "MIMIC-IV",
            "cohort": "same-patient complete-case N=409, events=49",
            "outcome": "30-day all-cause mortality",
            "effect_type": "HR",
            "gv_metric": "POCT-derived GV SD per 10 mg/dL",
            "source_definition": "same-patient POCT",
            "adjustment_set": "same-patient Model B contract",
            "existing_locked_estimate_available": True,
            "new_fit_required": False,
            "patient_level_available": True,
            "fit_status": "LOCKED_RESULT_AVAILABLE",
            "reason": "Locked same-patient result exists; agreement diagnostics are separate",
        },
        {
            "analysis_id": "MIMIC_SAMEPATIENT_LAB_30D",
            "database": "MIMIC-IV",
            "cohort": "same-patient complete-case N=409, events=49",
            "outcome": "30-day all-cause mortality",
            "effect_type": "HR",
            "gv_metric": "central-laboratory-derived GV SD per 10 mg/dL",
            "source_definition": "same-patient central laboratory",
            "adjustment_set": "same-patient Model B contract",
            "existing_locked_estimate_available": True,
            "new_fit_required": False,
            "patient_level_available": True,
            "fit_status": "LOCKED_RESULT_AVAILABLE",
            "reason": "Locked same-patient result exists; agreement diagnostics are separate",
        },
        {
            "analysis_id": "MIMIC_MEASUREMENT_PROCESS_CONTEXT",
            "database": "MIMIC-IV",
            "cohort": "final target plus source-context flags",
            "outcome": "measurement-process characterization",
            "effect_type": "DESCRIPTIVE/ASSOCIATION",
            "gv_metric": "GV SD, mean, count, span",
            "source_definition": "final source-priority and paired-source context",
            "adjustment_set": "Phase 2 specification to be declared before fitting",
            "existing_locked_estimate_available": False,
            "new_fit_required": True,
            "patient_level_available": True,
            "fit_status": "PLANNED_NOT_RUN",
            "reason": "Phase 1.6 registers the estimand only; sampling-process models are prohibited here",
        },
        {
            "analysis_id": "MIMIC_SAMEPATIENT_AGREEMENT_DIAGNOSTIC",
            "database": "MIMIC-IV",
            "cohort": "paired-source agreement-eligible cohort",
            "outcome": "paired GV measurement agreement",
            "effect_type": "DESCRIPTIVE",
            "gv_metric": "paired POCT and laboratory GV",
            "source_definition": "same-patient paired source file",
            "adjustment_set": "Not applicable",
            "existing_locked_estimate_available": False,
            "new_fit_required": True,
            "patient_level_available": True,
            "fit_status": "PLANNED_NOT_RUN",
            "reason": "No correlation or Bland–Altman analysis is run before Phase 2",
        },
        {
            "analysis_id": "EICU_M3",
            "database": "eICU-CRD",
            "cohort": "final aggregate harmonized M3 N=7115, events=130",
            "outcome": "post-landmark hospital mortality",
            "effect_type": "RR",
            "gv_metric": "aggregate GV SD per 10 mg/dL",
            "source_definition": "preserved aggregate all-source glucose features",
            "adjustment_set": "harmonized M3",
            "existing_locked_estimate_available": True,
            "new_fit_required": False,
            "patient_level_available": True,
            "fit_status": "LOCKED_RESULT_AVAILABLE",
            "reason": "Reconstructed eligibility mask and verified locked M3 fingerprint",
        },
        {
            "analysis_id": "EICU_M4",
            "database": "eICU-CRD",
            "cohort": "final aggregate harmonized M4 N=7115, events=130",
            "outcome": "post-landmark hospital mortality",
            "effect_type": "RR",
            "gv_metric": "aggregate GV SD per 10 mg/dL",
            "source_definition": "preserved aggregate all-source glucose features",
            "adjustment_set": "harmonized M4 plus count and span",
            "existing_locked_estimate_available": True,
            "new_fit_required": False,
            "patient_level_available": True,
            "fit_status": "LOCKED_RESULT_AVAILABLE",
            "reason": "Reconstructed eligibility mask and verified locked M4 fingerprint",
        },
        {
            "analysis_id": "EICU_EVENT_LEVEL_RECONSTRUCTION",
            "database": "eICU-CRD",
            "cohort": "event-level glucose reconstruction",
            "outcome": "post-landmark hospital mortality",
            "effect_type": "RR",
            "gv_metric": "event-level GV",
            "source_definition": "event-level eICU glucose series",
            "adjustment_set": "To be declared only if event-level data become available",
            "existing_locked_estimate_available": False,
            "new_fit_required": True,
            "patient_level_available": False,
            "fit_status": "NOT_FEASIBLE",
            "reason": "No separate event-level eICU glucose input is preserved in the final package",
        },
        {
            "analysis_id": "EICU_MIMIC_POOLING",
            "database": "MIMIC-IV plus eICU-CRD",
            "cohort": "cross-database comparison",
            "outcome": "non-equivalent database outcomes",
            "effect_type": "PROHIBITED_POOLING",
            "gv_metric": "database-specific GV scales",
            "source_definition": "MIMIC final priority versus eICU aggregate",
            "adjustment_set": "Not applicable",
            "existing_locked_estimate_available": False,
            "new_fit_required": False,
            "patient_level_available": True,
            "fit_status": "PROHIBITED",
            "reason": "Do not pool or claim interchangeability across non-equivalent HR/RR and measurement processes",
        },
        {
            "analysis_id": "INSPIRE_I2_24H",
            "database": "INSPIRE",
            "cohort": "24h landmark N=1353, events=27",
            "outcome": "30-day all-cause mortality",
            "effect_type": "HR",
            "gv_metric": "GV SD per 10 mg/dL",
            "source_definition": "INSPIRE final 24h anchor",
            "adjustment_set": "I2 final contract",
            "existing_locked_estimate_available": True,
            "new_fit_required": False,
            "patient_level_available": True,
            "fit_status": "LOCKED_RESULT_AVAILABLE",
            "reason": "Verified v5 locked I2 result and coverage attestation",
        },
        {
            "analysis_id": "INSPIRE_I2_48H",
            "database": "INSPIRE",
            "cohort": "48h landmark N=1511, events=31",
            "outcome": "30-day all-cause mortality",
            "effect_type": "HR",
            "gv_metric": "GV SD per 10 mg/dL",
            "source_definition": "INSPIRE final 48h landmark cohort",
            "adjustment_set": "I2 48h final contract",
            "existing_locked_estimate_available": True,
            "new_fit_required": False,
            "patient_level_available": True,
            "fit_status": "LOCKED_RESULT_AVAILABLE",
            "reason": "Verified v5 locked 48h result and coverage attestation",
        },
        {
            "analysis_id": "INSPIRE_365D",
            "database": "INSPIRE",
            "cohort": "final INSPIRE source cohort",
            "outcome": "365-day all-cause mortality",
            "effect_type": "HR",
            "gv_metric": "GV SD per 10 mg/dL",
            "source_definition": "INSPIRE v5 source data",
            "adjustment_set": "Not registered for Phase 2 without coverage decision",
            "existing_locked_estimate_available": False,
            "new_fit_required": False,
            "patient_level_available": True,
            "fit_status": "WITHDRAWN",
            "reason": "No common 365-day registry coverage end documented; do not reintroduce failed historical/withdrawn endpoint",
        },
    ]
    output_path = output_root(config) / "machine_readable" / "phase2_estimand_inventory.csv"
    write_csv(output_path, rows, FIELDS)
    status = {
        "generated_at_utc": utc_now_iso(),
        "status": "PASS",
        "modeling_performed": False,
        "row_count": len(rows),
        "output": str(output_path.resolve()),
    }
    log_path = workspace_root(config) / "logs" / "02_build_phase2_estimand_inventory.log"
    log_path.parent.mkdir(parents=True, exist_ok=True)
    log_path.write_text(json.dumps(status, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps(status, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
